on: push
  
jobs:
  fedora-test:
    runs-on: ubuntu-latest
    container: fedora:39
    steps:
      - run: |
          sudo chmod +x setup_script.sh
          ./setup_script.sh
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo chmod +x setup_script.sh
          ./setup_script.sh



