on: push
  
jobs:
  test-matrix:
    strategy:
      matrix:
        os: ["ubuntu-latest", "fedora:39"]

    runs-on: ubuntu-latest
    container: "${{matrix.os}}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
                
      - name: Run Test
        run: |
          sudo chmod +x setup.sh
          ./setup.sh